In [17]:
import numpy as np
from scipy.optimize import linprog

In [3]:

u1 = np.array([[2,1],[1,2]])
u2 = np.array([[1,2],[5,1]])

In [50]:
def game22(u1,u2):

  print(u1)
  alpha=(u1+u2).flatten()

  beta = -np.concatenate((u1[0]-u1[1],-u1[0]+u1[1]))
  gamma = -np.array((u2[0][0]-u2[0][1],u2[0][1]-u2[0][0],u2[1][0]-u2[1][1],u2[1][1]-u2[1][0]))
  print(gamma)
  c = -1*alpha
  A_in=[[beta[0],beta[1],0,0],[0,0,beta[2],beta[3]],[gamma[0],0,gamma[2],0],[0,gamma[1],0,gamma[3]]]

  B_in = np.zeros(len(c))
  A_e=np.array([np.ones(len(c))])
  B_e=1

  x0_bounds = (0,None)
  x1_bounds = (0,None)
  x2_bounds = (0,None)
  x3_bounds = (0,None)

  res = linprog(c,A_ub=A_in,b_ub=B_in,A_eq=A_e,b_eq=B_e,bounds=(x0_bounds,x0_bounds,x0_bounds,x0_bounds),options={"disp":True})

  print(res)

In [51]:
u1 = np.array([[2,1],[1,2]])
u2 = np.array([[1,2],[5,1]])
game22(u1,u2)

[[2 1]
 [1 2]]
[ 1 -1 -4  4]
Primal Feasibility  Dual Feasibility    Duality Gap         Step             Path Parameter      Objective          
1.0                 1.0                 1.0                 -                1.0                 -15.0               
0.2470575868614     0.2470575868614     0.2470575868614     0.7626703512929  0.2470575868614     -7.499056424899     
0.04863204704395    0.04863204704395    0.04863204704395    0.8264712364673  0.04863204704395    -3.952477848363     
0.001760080581663   0.001760080581861   0.001760080581861   0.9662219902259  0.001760080580982   -3.319106684702     
1.638658000282e-07  1.638657588316e-07  1.638657589937e-07  0.9999090882796  1.638659056265e-07  -3.300001772309     
8.215431271099e-12  8.2125703056e-12    8.212541757757e-12  0.9999498825414  8.225563695384e-12  -3.300000000089     
Optimization terminated successfully.
         Current function value: -3.300000   
         Iterations: 5
     con: array([-1.99498196e-11])
    

Q2 game 1 solution: [0.4,0.4,0.1,0.1]

Final reward: 3.3

In [52]:
u1 = np.array([[3,6],[2,7]])
u2 = np.array([[7,6],[2,3]])
game22(u1,u2)

[[3 6]
 [2 7]]
[-1  1  1 -1]
Primal Feasibility  Dual Feasibility    Duality Gap         Step             Path Parameter      Objective          
1.0                 1.0                 1.0                 -                1.0                 -36.0               
0.2687172985009     0.2687172985009     0.2687172985009     0.7381826685089  0.2687172985009     -35.03551208921     
0.08966205897697    0.08966205897697    0.08966205897697    0.6973930653663  0.08966205897697    -14.2702037624      
0.008560889539167   0.008560889538857   0.008560889538857   0.9174078500654  0.008560889539856   -11.00681962136     
3.763481925658e-06  3.763481924282e-06  3.763481924273e-06  0.9999121071037  3.763481929358e-06  -10.66679980447     
1.881759092998e-10  1.881757355089e-10  1.881757733762e-10  0.9999499995546  1.881749179615e-10  -10.66666667332     
Optimization terminated successfully.
         Current function value: -10.666667  
         Iterations: 5
     con: array([-6.69068356e-10])
    

Q2 game 2 solution: [3.33333334e-01, 3.33333333e-01, 4.74173892e-11, 3.33333334e-01]

Final reward: 10.6666

In [93]:
u1 = np.array([[7,6],[2,3]])
u2 = np.array([[3,6],[2,7]])
game22(u1,u2)

[[7 6]
 [2 3]]
[ 3 -3  5 -5]
Primal Feasibility  Dual Feasibility    Duality Gap         Step             Path Parameter      Objective          
1.0                 1.0                 1.0                 -                1.0                 -36.0               
0.1989321097656     0.1989321097656     0.1989321097656     0.8045347480697  0.1989321097656     -34.62419765843     
0.01475506009528    0.01475506009528    0.01475506009528    0.9639844171202  0.01475506009528    -13.68261206843     
1.29852215155e-05   1.298522151548e-05  1.29852215155e-05   0.9993054699716  1.29852215155e-05   -12.00100022549     
6.492690792451e-10  6.492691215669e-10  6.492691083184e-10  0.9999499993804  6.492690580914e-10  -12.00000005001     
Optimization terminated successfully.
         Current function value: -12.000000  
         Iterations: 4
     con: array([-6.45922715e-09])
     fun: -12.000000050013469
 message: 'Optimization terminated successfully.'
     nit: 4
   slack: array([ 3.00000001e+

Q2 game 3 solution: [2.77058254e-09, 9.99999999e-01, 2.05186553e-09, 2.77058254e-09]

Final reward: 12.000000050013469


In [94]:
def game23(u1,u2):

  print(u1)
  alpha=(u1+u2).flatten()

  beta = -np.concatenate((u1[0]-u1[1],-u1[0]+u1[1]))
  gamma = -np.array([[u2[0][0]-u2[0][1],0,0,u2[1][0]-u2[1][1],0,0],
                     [u2[0][0]-u2[0][2],0,0,u2[1][0]-u2[1][2],0,0],
                     [0,u2[0][1]-u2[0][0],0,0,u2[1][1]-u2[1][0],0],
                     [0,u2[0][1]-u2[0][2],0,0,u2[1][1]-u2[1][2],0],
                     [0,0,u2[0][2]-u2[0][0],0,0,u2[1][2]-u2[1][0]],
                     [0,0,u2[0][2]-u2[0][1],0,0,u2[1][2]-u2[1][1]]
                      ])
      
      
  print(gamma)
  c = -1*alpha
  
  A_in=np.concatenate((np.array([[beta[0],beta[1],beta[2],0,0,0],[0,0,0,beta[3],beta[4],beta[5]]]),gamma))
  print(A_in)
  B_in = np.zeros(len(A_in))
  A_e=np.array([np.ones(len(c))])
  B_e=1

  x0_bounds = (0,None)
  x1_bounds = (0,None)
  x2_bounds = (0,None)
  x3_bounds = (0,None)
  x4_bounds = (0,None)
  x5_bounds = (0,None)

  res = linprog(c,A_ub=A_in,b_ub=B_in,A_eq=A_e,b_eq=B_e,bounds=(x0_bounds,x1_bounds,x2_bounds,x3_bounds,x4_bounds,x5_bounds),options={"disp":True})

  print(res)

In [95]:
U1=np.array([[0,5,8],[2,6,5]])
U2=np.array([[4,6,7],[9,5,1]])
print(game23(U1,U2))

[[0 5 8]
 [2 6 5]]
[[ 2  0  0 -4  0  0]
 [ 3  0  0 -8  0  0]
 [ 0 -2  0  0  4  0]
 [ 0  1  0  0 -4  0]
 [ 0  0 -3  0  0  8]
 [ 0  0 -1  0  0  4]]
[[ 2  1 -3  0  0  0]
 [ 0  0  0 -2 -1  3]
 [ 2  0  0 -4  0  0]
 [ 3  0  0 -8  0  0]
 [ 0 -2  0  0  4  0]
 [ 0  1  0  0 -4  0]
 [ 0  0 -3  0  0  8]
 [ 0  0 -1  0  0  4]]
Primal Feasibility  Dual Feasibility    Duality Gap         Step             Path Parameter      Objective          
1.0                 1.0                 1.0                 -                1.0                 -58.0               
0.1817177707243     0.1817177707243     0.1817177707243     0.822077067551   0.1817177707243     -90.66477947571     
0.0842142261264     0.0842142261264     0.0842142261264     0.5563525095259  0.0842142261264     -33.54348748875     
0.007392027825124   0.007392027825124   0.007392027825124   0.9314407386832  0.007392027825124   -15.86359726942     
4.246995490861e-06  4.246995490933e-06  4.246995490928e-06  0.9998666000053  4.246995490893e-06 

Q3 game 1 solution: [2.51360500e-10, 6.48863322e-10, 1.00000000e+00;
 6.94663658e-10,
       5.68942640e-10, 6.72365849e-10]

Final reward: 15.000000028215803

In [91]:
def game_variable(U1,U2):
  n=len(U1)
  m=len(U1[0])

  A_in=np.zeros((n*(n-1)+m*(m-1),n*m))

  val = 0

  for i in range(n):
    for k in range(n):
      if i!=k:
        for j in range(m):
          A_in[val][i*m+j]=-U1[i][j]+U1[k][j]
        val+=1

  for j in range(m):
    for l in range(m):
      if j!=l:
        for j in range(n):
          A_in[val][i*m+j]=-U2[i][j]+U2[i][l]
        val+=1

  flat = -1*(U1+U2).flatten()
  print(flat)
  print("a_in",A_in)

  B_in=np.zeros(len(A_in))
  A_e=np.array([np.ones(len(flat))])

  B_e=1
  flat = -1*(U1+U2).flatten()
  bounds=[]

  for count in range(n*m):
    bounds.append((0,None))

  res = linprog(flat,A_ub=A_in,b_ub=B_in,A_eq=A_e,b_eq=B_e,bounds=bounds,options={"disp":True})

  print(res)

In [92]:
U1=np.array([[0,5,4],[4,0,5],[5,4,0]])
U2=np.array([[0,4,5],[5,0,4],[4,5,0]])


game_variable(U1,U2)

[ 0 -9 -9 -9  0 -9 -9 -9  0]
a_in [[ 4. -5.  1.  0.  0.  0.  0.  0.  0.]
 [ 5. -1. -4.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -4.  5. -1.  0.  0.  0.]
 [ 0.  0.  0.  1.  4. -5.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -5.  1.  4.]
 [ 0.  0.  0.  0.  0.  0. -1. -4.  5.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  5.]
 [ 0.  0.  0.  0.  0.  0.  0. -1.  4.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  5.]
 [ 0.  0.  0.  0.  0.  0.  0. -1.  4.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  5.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]]
Primal Feasibility  Dual Feasibility    Duality Gap         Step             Path Parameter      Objective          
1.0                 1.0                 1.0                 -                1.0                 -54.0               
0.1715631761739     0.1715631761739     0.1715631761739     0.8380594128471  0.1715631761739     -91.6990553467      
0.05024766845025    0.05024766845025    0.05024766845025    0.7567155632766  0.05024766845025    -33.10531748519     
0.007204052571699   0.0072

Q3 game 1 solution:[1.10981512e-10, 2.87111006e-01, 2.12888995e-01, 2.12888995e-01,
       1.10981512e-10, 2.87111006e-01, 5.62479739e-11, 1.33125337e-10,
       2.89880746e-11]

Final reward: 9.000000005766802